import Head from 'next/head'

function BaseHead() {
    return (
        <Head>
            <title>Test Project</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
        </Head>
    )
}

export default BaseHead